import type { Dictionary as PuckDictionary } from "@puckeditor/core";

export type StudioLang = "id" | "en";

const en = {
  // chrome
  studio: "Falah Studio",
  pages: "Pages",
  components: "Components",
  outline: "Structure",
  properties: "Properties",
  selectHint: "Select a section on the canvas to edit its content.",
  contentLanguage: "Content language",
  uiLanguage: "Interface",
  desktop: "Desktop",
  tablet: "Tablet",
  mobile: "Mobile",
  undo: "Undo",
  redo: "Redo",
  saveDraft: "Save draft",
  publish: "Publish",
  saving: "Saving…",
  saved: "Draft saved",
  published: "Published — the website updates in a few seconds.",
  unsaved: "Unsaved changes",
  upToDate: "All changes saved",
  backToCms: "Back to CMS",
  viewSite: "View page",
  sessionExpired: "Your CMS session has expired. Log in again in another tab, then retry.",
  forbidden: "You don't have permission to change this page.",
  switchLangConfirm: "You have unsaved changes. Switch language and discard them?",
  structureShared:
    "Section order and images are shared by all languages; texts are saved per language.",
  // auth screen
  loginTitle: "Sign in to continue",
  loginBody: "The visual editor uses your CMS account. Sign in to the CMS, then open this page again.",
  loginButton: "Open CMS login",
  notFoundTitle: "Page not found",
  // fields
  noImage: "No image",
  choose: "Choose image",
  replace: "Replace",
  remove: "Remove",
  close: "Close",
  upload: "Upload",
  searchImages: "Search images…",
  loadMore: "Load more",
  loading: "Loading…",
  addTag: "Type and press Enter",
  addItem: "+ Add…",
  // categories
  catSections: "Ready-made sections",
  catLayout: "Layout",
  catElements: "Elements (inside columns)",
};

export type StudioStrings = typeof en;

const id: StudioStrings = {
  studio: "Falah Studio",
  pages: "Halaman",
  components: "Komponen",
  outline: "Struktur",
  properties: "Properti",
  selectHint: "Pilih section di kanvas untuk mengedit isinya.",
  contentLanguage: "Bahasa konten",
  uiLanguage: "Tampilan",
  desktop: "Desktop",
  tablet: "Tablet",
  mobile: "Ponsel",
  undo: "Urungkan",
  redo: "Ulangi",
  saveDraft: "Simpan draft",
  publish: "Publish",
  saving: "Menyimpan…",
  saved: "Draft tersimpan",
  published: "Terpublish — website diperbarui dalam beberapa detik.",
  unsaved: "Ada perubahan belum disimpan",
  upToDate: "Semua perubahan tersimpan",
  backToCms: "Kembali ke CMS",
  viewSite: "Lihat halaman",
  sessionExpired: "Sesi CMS Anda berakhir. Login ulang di tab lain, lalu coba lagi.",
  forbidden: "Anda tidak punya izin mengubah halaman ini.",
  switchLangConfirm: "Ada perubahan yang belum disimpan. Ganti bahasa dan buang perubahan?",
  structureShared: "Urutan section dan gambar sama untuk semua bahasa; teks disimpan per bahasa.",
  loginTitle: "Masuk untuk melanjutkan",
  loginBody: "Editor visual memakai akun CMS Anda. Login ke CMS, lalu buka halaman ini lagi.",
  loginButton: "Buka login CMS",
  notFoundTitle: "Halaman tidak ditemukan",
  noImage: "Belum ada gambar",
  choose: "Pilih gambar",
  replace: "Ganti",
  remove: "Hapus",
  close: "Tutup",
  upload: "Unggah",
  searchImages: "Cari gambar…",
  loadMore: "Muat lagi",
  loading: "Memuat…",
  addTag: "Ketik lalu tekan Enter",
  addItem: "+ Tambah…",
  catSections: "Section siap pakai",
  catLayout: "Tata letak",
  catElements: "Elemen (di dalam kolom)",
};

export const studioStrings: Record<StudioLang, StudioStrings> = { en, id };

/** Puck's built-in UI strings in Indonesian (English is Puck's default). */
export const puckDictionaryId: PuckDictionary = {
  "header-publish": "Publish",
  "header-undo": "urungkan",
  "header-redo": "ulangi",
  "header-toggle-leftsidebar": "Buka/tutup panel kiri",
  "header-toggle-rightsidebar": "Buka/tutup panel kanan",
  "action-selectparent": "Pilih induk",
  "action-duplicate": "Duplikat",
  "action-delete": "Hapus",
  "label-page": "Halaman",
  "label-component": "Komponen",
  "outline-empty": "Belum ada item",
  "outline-item-collapse": "Ciutkan",
  "outline-item-expand": "Bentangkan",
  "outline-header-title": "Struktur",
  "outline-header-collapseall": "Ciutkan semua",
  "outline-item-duplicate": "Duplikat",
  "outline-item-delete": "Hapus",
  "drawer-category-collapse": "Ciutkan {title}",
  "drawer-category-expand": "Bentangkan {title}",
  "drawer-category-other": "Lainnya",
  "field-readonly": "Hanya baca",
  "field-arrayitem-summary": "Item #{index}",
  "field-arrayitem-duplicate": "Duplikat",
  "field-arrayitem-delete": "Hapus",
  "viewport-zoom-in": "Perbesar",
  "viewport-zoom-out": "Perkecil",
  "viewport-switch": "Beralih ke tampilan {label}",
  "plugin-blocks": "Blok",
  "plugin-outline": "Struktur",
  "plugin-fields": "Properti",
  "plugin-components": "Komponen",
  "loader-loading": "memuat",
};
