import type { Dictionary as PuckDictionary } from "@puckeditor/core";

export type StudioLang = "id" | "en";

const en = {
  contentLanguage: "Content language",
  desktop: "Desktop",
  tablet: "Tablet",
  mobile: "Mobile",
  saveDraft: "Save draft",
  saving: "Saving…",
  savingDraft: "Saving draft…",
  publishing: "Publishing…",
  saved: "Draft saved",
  published: "Published — the website updates in a few seconds.",
  backToCms: "Back to CMS",
  viewSite: "View page",
  sessionExpired: "Your CMS session has expired. Log in again in another tab, then retry.",
  forbidden: "You don't have permission to change this page.",
  structureShared:
    "Section order and images are shared by all languages; texts are saved per language.",
  // auth screen
  loginTitle: "Sign in to continue",
  loginBody: "The visual editor uses your CMS account. Sign in to the CMS, then open this page again.",
  loginButton: "Open CMS login",
  notFoundTitle: "Page not found",
  // fields
  noImage: "No image",
  noVideo: "No video",
  choose: "Choose image",
  chooseVideo: "Choose video",
  replace: "Replace",
  remove: "Remove",
  close: "Close",
  upload: "Upload",
  searchImages: "Search images…",
  searchVideos: "Search videos…",
  loadMore: "Load more",
  loading: "Loading…",
  addTag: "Type and press Enter",
  addItem: "+ Add…",
  createInCms: "New in CMS (opens a new tab) — refresh the editor after saving",
  interfaceLanguage: "Interface language",
  // categories
  catLayout: "Layout",
  catTypography: "Typography",
  catActions: "Actions",
  catMedia: "Media",
  catSections: "Sections",
};

export type StudioStrings = typeof en;

const id: StudioStrings = {
  contentLanguage: "Bahasa konten",
  desktop: "Desktop",
  tablet: "Tablet",
  mobile: "Ponsel",
  saveDraft: "Simpan draft",
  saving: "Menyimpan…",
  savingDraft: "Menyimpan draft…",
  publishing: "Mempublish…",
  saved: "Draft tersimpan",
  published: "Terpublish — website diperbarui dalam beberapa detik.",
  backToCms: "Kembali ke CMS",
  viewSite: "Lihat halaman",
  sessionExpired: "Sesi CMS Anda berakhir. Login ulang di tab lain, lalu coba lagi.",
  forbidden: "Anda tidak punya izin mengubah halaman ini.",
  structureShared: "Urutan section dan gambar sama untuk semua bahasa; teks disimpan per bahasa.",
  loginTitle: "Masuk untuk melanjutkan",
  loginBody: "Editor visual memakai akun CMS Anda. Login ke CMS, lalu buka halaman ini lagi.",
  loginButton: "Buka login CMS",
  notFoundTitle: "Halaman tidak ditemukan",
  noImage: "Belum ada gambar",
  noVideo: "Belum ada video",
  choose: "Pilih gambar",
  chooseVideo: "Pilih video",
  replace: "Ganti",
  remove: "Hapus",
  close: "Tutup",
  upload: "Unggah",
  searchImages: "Cari gambar…",
  searchVideos: "Cari video…",
  loadMore: "Muat lagi",
  loading: "Memuat…",
  addTag: "Ketik lalu tekan Enter",
  addItem: "+ Tambah…",
  createInCms: "Buat baru di CMS (tab baru) — refresh editor setelah disimpan",
  interfaceLanguage: "Bahasa tampilan",
  catLayout: "Tata Letak",
  catTypography: "Tipografi",
  catActions: "Aksi",
  catMedia: "Media",
  catSections: "Section",
};

export const studioStrings: Record<StudioLang, StudioStrings> = { en, id };

/** Puck's built-in UI strings in Indonesian (English is Puck's default). */
export const puckDictionaryId: PuckDictionary = {
  "header-publish": "Publish",
  "header-undo": "urungkan",
  "header-redo": "ulangi",
  "header-toggle-leftsidebar": "Buka/tutup panel kiri",
  "header-toggle-rightsidebar": "Buka/tutup panel kanan",
  "action-selectparent": "Pilih induk",
  "action-duplicate": "Duplikat",
  "action-delete": "Hapus",
  "label-page": "Halaman",
  "label-component": "Komponen",
  "outline-empty": "Belum ada item",
  "outline-item-collapse": "Ciutkan",
  "outline-item-expand": "Bentangkan",
  "outline-header-title": "Struktur",
  "outline-header-collapseall": "Ciutkan semua",
  "outline-item-duplicate": "Duplikat",
  "outline-item-delete": "Hapus",
  "drawer-category-collapse": "Ciutkan {title}",
  "drawer-category-expand": "Bentangkan {title}",
  "drawer-category-other": "Lainnya",
  "field-readonly": "Hanya baca",
  "field-arrayitem-summary": "Item #{index}",
  "field-arrayitem-duplicate": "Duplikat",
  "field-arrayitem-delete": "Hapus",
  "viewport-zoom-in": "Perbesar",
  "viewport-zoom-out": "Perkecil",
  "viewport-switch": "Beralih ke tampilan {label}",
  "plugin-blocks": "Blok",
  "plugin-outline": "Struktur",
  "plugin-fields": "Properti",
  "plugin-components": "Komponen",
  "loader-loading": "memuat",
};
